springdoc:
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 경로
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs  # OpenAPI 명세 경로
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**